[Node]
DataDir = "/ethclient/geth"

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
ListenAddr = ":33000"

StaticNodes = [
  "enode://bebcc5c7381459460213ef4004c37c205eec64c1b218b1ee1738923b10d81858164b8d993596365028e860c3abe78679faddf68ae2581a9a86b860ea30f8d191@57.128.20.31:32000",
  "enode://c5cd35b9916952de2ce017ddd130be881508e101bf3121079f3dcec74a4093ab6f1cd16eca666c4b2ba3bc155261650dda7a622fba2939d1e95a4d64e5f2eca9@57.128.20.31:32007",
]

TrustedNodes = [
  "enode://bebcc5c7381459460213ef4004c37c205eec64c1b218b1ee1738923b10d81858164b8d993596365028e860c3abe78679faddf68ae2581a9a86b860ea30f8d191@57.128.20.31:32000",
  "enode://c5cd35b9916952de2ce017ddd130be881508e101bf3121079f3dcec74a4093ab6f1cd16eca666c4b2ba3bc155261650dda7a622fba2939d1e95a4d64e5f2eca9@57.128.20.31:32007",
]
