[Node.P2P]
StaticNodes = [
  "enode://e90c7d3640a1568839c31b70a893ab6714ef8415b9de90cedfc1c8f353a6983e625529392df7fa514bdd65a2003f6619567d79bee89830e63e932dbd42362d34@192.99.8.196:40303",
  "enode://e8de24dcde8c61cbb02dbe6ecf2e911bbe522542f1a081822e83ea7baf83640785a5dc9cf4112cfdb24dd210911eb50053b46b4368400a609b850780134ea94a@192.99.8.196:40304"
]
